#!/usr/bin/env python3
"""
Extract @impl and @verifies trace tags from source code and tests,
emit a Sphinx-Needs RST file linking implementations and tests to LLRs.

Tag formats supported (in any line-comment style):
    @impl LLR-IMU-001
    @impl LLR-IMU-001, LLR-IMU-002
    \\impl LLR-IMU-001            (Doxygen-style backslash also accepted)
    @verifies LLR-IMU-001

Constraints:
    - All IDs for one tag must be on a single line. Multi-line continuations
      are not supported (keeps the scanner simple and unambiguous).
    - @impl tags belong in src/lib; @verifies tags belong in tests.
      Misplaced tags produce a warning but are still emitted.

Usage:
    python tools/extract_trace_tags.py \\
        --src src lib \\
        --tests tests \\
        --output docs/_generated/trace_tags.rst
"""

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

# Capture (kind, comma-separated id list). Requirement IDs match the project
# scheme in NTR-REQSTD-001: uppercase letters, digits, hyphens, underscores.
TAG_RE = re.compile(
    r"[@\\](impl|verifies)\s+"
    r"([A-Z][A-Z0-9_-]*(?:\s*,\s*[A-Z][A-Z0-9_-]*)*)"
)

SOURCE_EXTENSIONS = {".c", ".h", ".cpp", ".hpp", ".cc", ".hh"}
TEST_EXTENSIONS = SOURCE_EXTENSIONS | {".py"}


def find_tags(root, extensions):
    """Yield (path, line_no, kind, [ids]) for every tag found under root."""
    for path in root.rglob("*"):
        if not path.is_file() or path.suffix not in extensions:
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        for line_no, line in enumerate(text.splitlines(), start=1):
            for match in TAG_RE.finditer(line):
                kind = match.group(1)
                ids = [s.strip() for s in match.group(2).split(",")]
                yield path, line_no, kind, ids


def sanitize(name):
    """Make a string safe to embed in a need ID."""
    return re.sub(r"[^A-Za-z0-9]", "_", name)


def emit_rst(impls, tests, output, repo_root):
    """Write the generated trace_tags.rst file."""
    lines = [
        ".. AUTO-GENERATED by tools/extract_trace_tags.py. Do not edit by hand.",
        ".. Edit @impl / @verifies tags in source files instead.",
        "",
        "Code Trace Tags",
        "===============",
        "",
        "Implementations",
        "---------------",
        "",
    ]

    def append_section(records, directive, id_prefix, link_attr):
        counter = defaultdict(int)
        for path, line_no, _, ids in records:
            try:
                rel = path.relative_to(repo_root)
            except ValueError:
                rel = path
            for llr_id in ids:
                base = f"{id_prefix}_{llr_id}"
                counter[base] += 1
                n = counter[base]
                need_id = base if n == 1 else f"{base}_{n}"
                lines.extend([
                    f".. {directive}:: {rel}:{line_no}",
                    f"   :id: {need_id}",
                    f"   :{link_attr}: {llr_id}",
                    "",
                    f"   Found in ``{rel}`` at line {line_no}.",
                    "",
                ])

    append_section(impls, "impl", "IMPL", "implements")
    lines.extend(["Tests", "-----", ""])
    append_section(tests, "test", "TEST", "verifies")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")


def collect(dirs, extensions, expected_kind, label):
    """Walk dirs, sort tags by expected_kind vs other; warn on mismatches."""
    matching, other = [], []
    for d in dirs:
        if not d.exists():
            print(f"warning: {label} dir does not exist: {d}", file=sys.stderr)
            continue
        for record in find_tags(d, extensions):
            path, line_no, kind, _ = record
            if kind == expected_kind:
                matching.append(record)
            else:
                print(
                    f"warning: @{kind} tag in {label} tree at {path}:{line_no} "
                    f"(expected @{expected_kind} here)",
                    file=sys.stderr,
                )
                other.append(record)
    return matching, other


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--src", nargs="+", type=Path,
                   default=[Path("src"), Path("lib")])
    p.add_argument("--tests", nargs="+", type=Path,
                   default=[Path("tests")])
    p.add_argument("--output", type=Path,
                   default=Path("docs/_generated/trace_tags.rst"))
    p.add_argument("--repo-root", type=Path, default=Path.cwd())
    args = p.parse_args()

    src_impls, src_other = collect(args.src, SOURCE_EXTENSIONS, "impl", "src")
    test_verifies, test_other = collect(args.tests, TEST_EXTENSIONS, "verifies", "tests")

    impls = src_impls + test_other         # @impl tags from either tree
    tests = test_verifies + src_other      # @verifies tags from either tree

    emit_rst(impls, tests, args.output, args.repo_root)
    print(f"wrote {len(impls)} impl(s) and {len(tests)} test(s) to {args.output}")


if __name__ == "__main__":
    main()
